language: python
python:
  - "3.6"
install:
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install coverage
  - pip install .
script: pytest --cov=metriks tests/
after_success:
  - coveralls